// vehicle_paint_profiles_tests: the table a respray looks a car's paint up in
// (game/vehicle_paint_profiles.h), and the rule that every drivable car has a
// profile or is explicitly pending (app/vehicle_paint_catalog.h).
//
// The table is generated from tools/paint_profiles/*.json by `python3
// tools/paint_profiles.py emit`. This suite cannot rerun the lab -- that needs
// numpy, and the PNG decoder lives in the host layer -- so it holds the
// generated file to its sources by digest and checks everything a table can
// get wrong on its own. `tools/paint_profiles.py check` and `lamps` are the
// by-hand half, run against the real PNGs.
#include "app/vehicle_paint_catalog.h"
#include "game/vehicle_paint_profiles.h"
#include "test_assert.h"

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

using namespace apricot;

namespace {

constexpr std::string_view kVehicleTextures = "textures/vehicles/";
constexpr const char* kTableHeader = "// GENERATED by tools/paint_profiles.py emit -- do not edit";
constexpr uint64_t kFnvOffset = 0xcbf29ce484222325ull;
constexpr uint64_t kFnvPrime = 0x100000001b3ull;

// The fix, spelled out, for whoever adds a car next. docs/architecture.md
// (Rendering) says why the rule exists and what it costs.
constexpr const char* kMissingProfile =
    "add PlayerCarId::X to kPaintProfilePending in src/app/vehicle_paint_catalog.h, "
    "or add tools/paint_profiles/<slug>.json and run tools/paint_profiles.py emit";

std::filesystem::path repo_path(const char* relative) {
    return std::filesystem::path(APRICOT_ASSETS_DIR) / ".." / relative;
}

bool read_file(const std::filesystem::path& path, std::string& out) {
    std::ifstream in(path, std::ios::binary);
    if (!in) return false;
    std::ostringstream bytes;
    bytes << in.rdbuf();
    out = bytes.str();
    return true;
}

// FNV-1a 64, carriage returns skipped, as tools/paint_profiles.py digests.
uint64_t fnv1a64(uint64_t h, std::string_view bytes) {
    for (char c : bytes) {
        if (c == '\r') continue;
        h ^= static_cast<uint64_t>(static_cast<unsigned char>(c));
        h *= kFnvPrime;
    }
    return h;
}

bool starts_with(std::string_view s, std::string_view prefix) {
    return s.size() >= prefix.size() && s.substr(0, prefix.size()) == prefix;
}

bool ends_with(std::string_view s, std::string_view suffix) {
    return s.size() >= suffix.size() && s.substr(s.size() - suffix.size()) == suffix;
}

bool atlas_path_ok(const char* path) {
    return path && starts_with(path, kVehicleTextures) && ends_with(path, ".png");
}

// Width and height from a PNG's IHDR chunk, which always follows the
// signature: bytes 16-19 and 20-23, big-endian.
bool png_size(const std::filesystem::path& path, int& width, int& height) {
    std::string bytes;
    if (!read_file(path, bytes) || bytes.size() < 24 || bytes.compare(12, 4, "IHDR") != 0) return false;
    auto be32 = [&](std::size_t at) {
        uint32_t v = 0;
        for (std::size_t i = 0; i < 4; ++i) {
            v = (v << 8) | static_cast<uint32_t>(static_cast<unsigned char>(bytes[at + i]));
        }
        return static_cast<int>(v);
    };
    width = be32(16);
    height = be32(20);
    return true;
}

bool rect_ok(const UvRect& r) {
    return 0.0f <= r.u0 && r.u0 < r.u1 && r.u1 <= 1.0f &&
           0.0f <= r.v0 && r.v0 < r.v1 && r.v1 <= 1.0f;
}

// Whether any texel centre of a w x h atlas lies in the rect, by the port's
// half-open rule. A box reference that covers none has no colour.
bool rect_covers_a_texel(const UvRect& r, int w, int h) {
    bool column = false, row = false;
    for (int x = 0; x < w && !column; ++x) {
        const double c = (x + 0.5) / w;
        column = r.u0 <= c && c < r.u1;
    }
    for (int y = 0; y < h && !row; ++y) {
        const double c = (y + 0.5) / h;
        row = r.v0 <= c && c < r.v1;
    }
    return column && row;
}

bool tol_ok(const PaintTol& t) {
    return t.c >= 0.0f && t.fc > 0.0f && t.dark >= 0.0f && t.light >= 0.0f && t.fl > 0.0f;
}

template <typename T>
bool list_ok(const T* items, uint16_t count) {
    return (count == 0) == (items == nullptr);
}

void check_params(const PaintMaskParams& p, int w, int h, const char* atlas) {
    REQUIRE_MSG(p.refs && p.ref_count > 0, "a profile needs at least one paint reference", atlas);
    REQUIRE_MSG(list_ok(p.exclude_refs, p.exclude_ref_count) && list_ok(p.include, p.include_count) &&
                    list_ok(p.exclude, p.exclude_count) && list_ok(p.force, p.force_count),
                "a list's pointer is null exactly when its count is 0", atlas);
    auto check_refs = [&](const PaintRef* refs, uint16_t count) {
        for (uint16_t i = 0; i < count; ++i) {
            REQUIRE_MSG(tol_ok(refs[i].tol), "tolerances are >= 0, and fc and fl are > 0", atlas);
            if (refs[i].kind == PaintRef::Kind::Box) {
                REQUIRE_MSG(rect_ok(refs[i].box) && rect_covers_a_texel(refs[i].box, w, h),
                            "a box reference must cover at least one texel centre", atlas);
            }
        }
    };
    check_refs(p.refs, p.ref_count);
    check_refs(p.exclude_refs, p.exclude_ref_count);
    for (const auto& [rects, count] : {std::pair{p.include, p.include_count},
                                       std::pair{p.exclude, p.exclude_count},
                                       std::pair{p.force, p.force_count}}) {
        for (uint16_t i = 0; i < count; ++i) {
            REQUIRE_MSG(rect_ok(rects[i]), "rects satisfy 0 <= u0 < u1 <= 1 and 0 <= v0 < v1 <= 1", atlas);
        }
    }
    REQUIRE_MSG(p.grow_dark >= 0.0f && p.grow_light >= 0.0f, "grow windows are >= 0", atlas);
}

void every_drivable_car_has_a_profile_or_is_pending() {
    std::size_t profiled_cars = 0;
    for (std::size_t i = 0; i < kPlayerCarCount; ++i) {
        const auto id = static_cast<PlayerCarId>(i);
        const PlayerCarDefinition& car = player_car_definition(id);
        const char* atlas = player_car_body_texture_path(id);
        char tag[320];
        std::snprintf(tag, sizeof tag, "X = %s %s (PlayerCarId value %zu), which wears %s",
                      car.brand, car.model, i, atlas);
        REQUIRE_MSG(car.id == canonical_player_car_id(id),
                    "a PlayerCarId has no kPlayerCars row, so the atlas it wears is unknown", tag);
        const bool profiled = find_paint_atlas_profile(atlas) != nullptr;
        const bool pending = player_car_paint_pending(id);
        REQUIRE_MSG(profiled || pending, kMissingProfile, tag);
        REQUIRE_MSG(!(profiled && pending),
                    "a car in kPaintProfilePending has a paint profile: delete its entry in "
                    "src/app/vehicle_paint_catalog.h",
                    tag);
        profiled_cars += profiled ? 1u : 0u;
    }
    for (PlayerCarId pending : kPaintProfilePending) {
        REQUIRE_MSG(static_cast<std::size_t>(pending) < kPlayerCarCount,
                    "kPaintProfilePending holds a value that is not a PlayerCarId", nullptr);
    }
    // The pending list is the exception, not a place to park cars.
    REQUIRE(profiled_cars + kPaintProfilePending.size() >= kPlayerCarCount);
    apricot_test::pass("every drivable car has a paint profile or is pending");
}

void body_texture_path_is_the_catalog_but_workman() {
    for (const PlayerCarDefinition& car : kPlayerCars) {
        const std::string_view worn = player_car_body_texture_path(car.id);
        // A plow truck wears its base truck's atlas, Workman's included.
        if (player_car_body_id(car.id) == PlayerCarId::HarrowWorkman) {
            REQUIRE(worn == "textures/vehicles/harrow_workman/body.png");
            REQUIRE(worn != car.texture_path);
        } else {
            REQUIRE_MSG(worn == car.texture_path, "only Workman wears an atlas its row does not name", car.model);
        }
    }
    REQUIRE(std::string_view(player_car_body_texture_path(PlayerCarId::LegacyCruiser91CSlot)) ==
            player_car_body_texture_path(PlayerCarId::MunicipalCruiser91C));
    // A constant expression, so a pending check can sit in a static_assert.
    static_assert(!player_car_paint_pending(PlayerCarId::VesperMistral));
    apricot_test::pass("the worn atlas is the catalog's, except Workman's semantic body.png");
}

void every_profile_is_well_formed() {
    const std::size_t count = paint_atlas_profile_count();
    REQUIRE(count > 0);
    for (std::size_t i = 0; i < count; ++i) {
        const PaintAtlasProfile& p = paint_atlas_profile(i);
        REQUIRE_MSG(atlas_path_ok(p.atlas), "an atlas is textures/vehicles/<model>/<name>.png", p.atlas);
        if (i > 0) {
            REQUIRE_MSG(std::string_view(paint_atlas_profile(i - 1).atlas) < p.atlas,
                        "profiles are unique and ordered by atlas path", p.atlas);
        }
        REQUIRE_MSG((p.width == 128 || p.width == 256) && p.height == p.width,
                    "atlases are 128 or 256 square", p.atlas);
        REQUIRE_MSG(p.grade == PaintGrade::Exact || p.grade == PaintGrade::Good || p.grade == PaintGrade::Rough,
                    "a grade is exact, good or rough", p.atlas);
        if (p.alias_of) {
            REQUIRE_MSG(!p.params && !p.region_atlas && !p.region_params && p.expect.painted_texels == 0,
                        "an alias carries no params or stats of its own", p.atlas);
            const PaintAtlasProfile* target = find_paint_atlas_profile(p.atlas);
            REQUIRE_MSG(target && std::string_view(target->atlas) == p.alias_of,
                        "an alias names an atlas that has its own profile", p.atlas);
            REQUIRE_MSG(target->width == p.width && target->height == p.height,
                        "an alias and its atlas are the same size", p.atlas);
            continue;
        }
        REQUIRE_MSG(find_paint_atlas_profile(p.atlas) == &p, "a lookup finds the profile itself", p.atlas);
        REQUIRE_MSG(p.params != nullptr, "a profile has params", p.atlas);
        check_params(*p.params, p.width, p.height, p.atlas);
        REQUIRE_MSG((p.region_atlas == nullptr) == (p.region_params == nullptr),
                    "region_params is set exactly when region_atlas is", p.atlas);
        if (p.region_atlas) {
            REQUIRE_MSG(atlas_path_ok(p.region_atlas) && std::string_view(p.region_atlas) != p.atlas,
                        "a region is another atlas", p.atlas);
            check_params(*p.region_params, p.width, p.height, p.region_atlas);
            int rw = 0, rh = 0;
            REQUIRE_MSG(png_size(repo_path("assets") / p.region_atlas, rw, rh) && rw == p.width &&
                            rh == p.height,
                        "a region atlas exists and matches its alternate's size", p.region_atlas);
        }
        const uint64_t texels = uint64_t{p.width} * p.height;
        REQUIRE_MSG(p.expect.painted_texels > 0 && p.expect.painted_texels <= texels,
                    "a profile paints something, and no more texels than the atlas has", p.atlas);
        // Every texel at weight >= .5 contributes at least nearbyint(127.5) = 128.
        REQUIRE_MSG(p.expect.weight_sum_q8 >= 128u * p.expect.painted_texels &&
                        p.expect.weight_sum_q8 <= 255u * texels,
                    "the weight sum agrees with the painted texel count", p.atlas);
        // The atlas the table was generated from is still the size it was.
        int w = 0, h = 0;
        REQUIRE_MSG(png_size(repo_path("assets") / p.atlas, w, h), "the atlas exists and is a PNG", p.atlas);
        REQUIRE_MSG(w == p.width && h == p.height,
                    "the atlas changed size since the table was generated: rerun tools/paint_profiles.py "
                    "check, then emit",
                    p.atlas);
    }
    apricot_test::pass("every profile is well formed and its atlas is on disk");
}

void generated_table_matches_its_sources() {
    namespace fs = std::filesystem;
    const fs::path dir = repo_path("tools/paint_profiles");
    std::vector<std::string> names;
    for (const fs::directory_entry& entry : fs::directory_iterator(dir)) {
        if (entry.is_regular_file() && entry.path().extension() == ".json") {
            names.push_back(entry.path().filename().string());
        }
    }
    std::sort(names.begin(), names.end());
    REQUIRE_MSG(!names.empty(), "no paint profiles found", dir.string().c_str());
    uint64_t json = kFnvOffset;
    for (const std::string& name : names) {
        std::string bytes;
        REQUIRE_MSG(read_file(dir / name, bytes), "a paint profile could not be read", name.c_str());
        json = fnv1a64(json, name);
        json = fnv1a64(json, std::string_view("\0", 1));
        json = fnv1a64(json, bytes);
    }

    std::string table;
    REQUIRE_MSG(read_file(repo_path("src/game/vehicle_paint_profiles.inc"), table),
                "src/game/vehicle_paint_profiles.inc could not be read", nullptr);
    const std::size_t end0 = table.find('\n');
    const std::size_t end1 = end0 == std::string::npos ? end0 : table.find('\n', end0 + 1);
    const std::size_t end2 = end1 == std::string::npos ? end1 : table.find('\n', end1 + 1);
    REQUIRE_MSG(end2 != std::string::npos, "the table lost its three header lines", nullptr);
    auto line = [&](std::size_t from, std::size_t to) {
        std::string s = table.substr(from, to - from);
        if (!s.empty() && s.back() == '\r') s.pop_back();
        return s;
    };
    const std::string header = line(0, end0);
    const std::string json_line = line(end0 + 1, end1);
    const std::string body_line = line(end1 + 1, end2);
    REQUIRE(header == kTableHeader);
    constexpr std::string_view kJsonPrefix = "// json-fnv1a64: 0x";
    constexpr std::string_view kBodyPrefix = "// body-fnv1a64: 0x";
    REQUIRE(starts_with(json_line, kJsonPrefix) && starts_with(body_line, kBodyPrefix));
    const auto header_json = static_cast<uint64_t>(std::strtoull(json_line.c_str() + kJsonPrefix.size(), nullptr, 16));
    const auto header_body = static_cast<uint64_t>(std::strtoull(body_line.c_str() + kBodyPrefix.size(), nullptr, 16));

    REQUIRE_MSG(json == header_json,
                "tools/paint_profiles/*.json changed and the table was not regenerated: run "
                "python3 tools/paint_profiles.py emit",
                nullptr);
    REQUIRE_MSG(fnv1a64(kFnvOffset, std::string_view(table).substr(end2 + 1)) == header_body,
                "src/game/vehicle_paint_profiles.inc was edited by hand: run python3 tools/paint_profiles.py emit",
                nullptr);
    REQUIRE_MSG(paint_profiles_json_digest() == json,
                "this build compiled a table generated from other JSON: rebuild", nullptr);
    apricot_test::pass("the compiled table is the one tools/paint_profiles/*.json generates");
}

void aliases_and_regions_resolve() {
    const PaintAtlasProfile* body = find_paint_atlas_profile("textures/vehicles/car5/body.png");
    const PaintAtlasProfile* taxi = find_paint_atlas_profile("textures/vehicles/car5/taxi.png");
    REQUIRE(body != nullptr && taxi == body);
    bool raw_taxi = false;
    for (std::size_t i = 0; i < paint_atlas_profile_count(); ++i) {
        const PaintAtlasProfile& p = paint_atlas_profile(i);
        if (std::string_view(p.atlas) != "textures/vehicles/car5/taxi.png") continue;
        raw_taxi = true;
        REQUIRE(p.alias_of != nullptr && std::string_view(p.alias_of) == "textures/vehicles/car5/body.png");
    }
    REQUIRE(raw_taxi);

    // Car 5's liveries are bounded by its stock mask, and so is the Car 8
    // ambulance, whose region is an atlas it does not wear.
    const PaintAtlasProfile* green = find_paint_atlas_profile("textures/vehicles/car5/green.png");
    REQUIRE(green && green->region_atlas && std::string_view(green->region_atlas) == body->atlas);
    REQUIRE(green->region_params == body->params);
    const PaintAtlasProfile* ambulance = find_paint_atlas_profile("textures/vehicles/car8/ambulance.png");
    REQUIRE(ambulance && ambulance->region_atlas &&
            std::string_view(ambulance->region_atlas) == "textures/vehicles/car8/body.png");
    REQUIRE(body->region_atlas == nullptr);

    REQUIRE(find_paint_atlas_profile("textures/vehicles/fang_venom/body.png") == nullptr);
    REQUIRE(find_paint_atlas_profile("") == nullptr);
    REQUIRE(find_paint_atlas_profile("car5/body.png") == nullptr);
    apricot_test::pass("taxi resolves to car5/body.png, and alternates carry their region");
}

// A stolen traffic car keeps the livery it was driving in, as a paint base,
// and a respray recolours that atlas. So every traffic livery needs a profile
// (or its player car is pending), and the base a theft records must name the
// very atlas traffic drew the car in.
void traffic_liveries_have_profiles_and_bases() {
    constexpr TrafficVehicleKind kKinds[] = {
        TrafficVehicleKind::Sedan, TrafficVehicleKind::BoxTruck, TrafficVehicleKind::Ambulance,
        TrafficVehicleKind::Firetruck, TrafficVehicleKind::HalcyonSix,
        TrafficVehicleKind::MontroseRegentEight, TrafficVehicleKind::VesperVx91,
        TrafficVehicleKind::Police, TrafficVehicleKind::Snowplow,
    };
    std::size_t liveries = 0;
    for (TrafficVehicleKind kind : kKinds) {
        const TrafficPaintPaths paths = traffic_paint_paths(kind);
        const PlayerCarId car = traffic_player_car(kind);
        if (kind == TrafficVehicleKind::Snowplow) {
            REQUIRE_MSG(paths.paths == nullptr && paths.count == 0,
                        "the snowplow is procedural flat white and wears no atlas", nullptr);
            REQUIRE(paint_base_for_traffic(kind, 0) == 0);
            continue;
        }
        REQUIRE_MSG(paths.paths != nullptr && paths.count > 0, "a traffic kind wears an atlas", nullptr);
        for (std::size_t i = 0; i < paths.count; ++i) {
            const char* path = paths.paths[i];
            ++liveries;
            REQUIRE_MSG(find_paint_atlas_profile(path) != nullptr || player_car_paint_pending(car),
                        kMissingProfile, path);
            const char* worn = player_car_paint_base_atlas(car, paint_base_for_traffic(kind, i));
            REQUIRE_MSG(worn != nullptr && std::string_view(worn) == path,
                        "a stolen car's paint base names the atlas traffic drew it in", path);
        }
    }
    REQUIRE(liveries == 14u);  // Car 5 and Car 8 four each, six single-livery kinds
    REQUIRE(paint_base_for_traffic(TrafficVehicleKind::Sedan, 99) == 0);
    apricot_test::pass("every traffic livery is profiled, and a theft records the base it was drawn in");
}

// APRICOT_SAVE 4 stores Car 5's and Car 8's livery as an index into these
// lists, so their order is a saved ID. A reorder must fail here, not in a save.
void saved_livery_order_is_pinned() {
    constexpr const char* kCar5[] = {
        "textures/vehicles/car5/body.png", "textures/vehicles/car5/green.png",
        "textures/vehicles/car5/grey.png", "textures/vehicles/car5/taxi.png",
    };
    constexpr const char* kCar8[] = {
        "textures/vehicles/car8/body.png", "textures/vehicles/car8/grey.png",
        "textures/vehicles/car8/purple.png", "textures/vehicles/car8/mail.png",
    };
    REQUIRE(player_car_paint_base_count(PlayerCarId::LegacyCar5) >= 4u);
    REQUIRE(player_car_paint_base_count(PlayerCarId::LegacyCar8) >= 4u);
    for (uint8_t i = 0; i < 4u; ++i) {
        REQUIRE_MSG(std::string_view(player_car_paint_base_atlas(PlayerCarId::LegacyCar5, i)) == kCar5[i],
                    "kCar5Paints is a saved ID: append only, never reorder", kCar5[i]);
        REQUIRE_MSG(std::string_view(player_car_paint_base_atlas(PlayerCarId::LegacyCar8, i)) == kCar8[i],
                    "kCar8Paints is a saved ID: append only, never reorder", kCar8[i]);
    }
    REQUIRE(paint_base_valid(PlayerCarId::LegacyCar8, 3));
    REQUIRE(!paint_base_valid(PlayerCarId::AlderPip, 1));
    REQUIRE(player_car_paint_base_atlas(PlayerCarId::AlderPip, 1) == nullptr);
    REQUIRE(paint_base_valid(PlayerCarId::LegacyCruiser91CSlot, 0));
    REQUIRE(!paint_base_valid(PlayerCarId::LegacyCruiser91CSlot, 1));
    for (std::size_t i = 0; i < kPlayerCarCount; ++i) {
        const auto id = static_cast<PlayerCarId>(i);
        const char* base0 = player_car_paint_base_atlas(id, 0);
        REQUIRE_MSG(base0 != nullptr && std::string_view(base0) == player_car_body_texture_path(id),
                    "base 0 is the atlas the car's catalog row loads", player_car_definition(id).model);
    }
    apricot_test::pass("the saved Car 5 and Car 8 livery order is pinned, and base 0 is the catalog atlas");
}

}  // namespace

int main() {
    every_drivable_car_has_a_profile_or_is_pending();
    body_texture_path_is_the_catalog_but_workman();
    every_profile_is_well_formed();
    generated_table_matches_its_sources();
    aliases_and_regions_resolve();
    traffic_liveries_have_profiles_and_bases();
    saved_livery_order_is_pinned();
    return apricot_test::done("vehicle_paint_profiles_tests");
}
