#pragma once

#include <cstdint>

#include "audio/mixer.h"
#include "audio/synth.h"

namespace apricot {

// The audio output device — the ONLY part of the audio module that touches
// hardware, which is exactly why it is the only part that lives in
// apricot_host. Gain maths (mixer.h) and waveform generation (synth.h) sit in
// the sim library and are tested with no device present.
//
// The playback callback runs on an OS-owned audio thread. Anything it reads
// must be safe to read there: no allocation, no locks, no logging. That
// contract is discharged by VoiceMixer, which this class does little more than
// pump — see mixer.h for how.
//
// SILENCE IS A SUPPORTED OUTCOME. A machine with no sound card, a CI runner, a
// container, a user who unplugged their interface: all of them get a fully
// working AudioDevice whose output goes nowhere. Every call below stays legal
// and cheap when start() returned false, so no caller anywhere needs to guard
// its audio code with an `if (audio_ok)`. Audio is never load-bearing for the
// app starting.
class AudioDevice {
public:
    AudioDevice() = default;
    ~AudioDevice();

    AudioDevice(const AudioDevice&) = delete;
    AudioDevice& operator=(const AudioDevice&) = delete;

    // Open the default output device, synthesise the sound bank, and begin
    // pulling from the mixer on the audio thread.
    //
    // Returns false when no device could be opened. That is a normal result,
    // not an error: the object stays usable and silent, and the bank is left
    // empty so no time is spent generating PCM nothing will ever play. A false
    // return means "no audio this session"; carry on.
    bool start();

    // Idempotent. Stops the device, cuts every voice, and leaves the bank
    // alone — the audio thread is gone before this returns, so the bank's
    // storage is safe to touch again afterwards.
    void stop();

    bool running() const { return running_; }

    // The device's actual rate, which is whatever the hardware wanted. 0 until
    // start() succeeds.
    uint32_t sample_rate() const { return sample_rate_; }

    // The voice mixer. Safe to drive from the sim thread whether or not a
    // device ever opened.
    VoiceMixer& mixer() { return mixer_; }
    const VoiceMixer& mixer() const { return mixer_; }

    // Every synthesised sound, generated by start(). EMPTY when start() failed
    // or has not been called — every clip pointer handed out by the *_mix()
    // functions is then null, which the mixer already treats as silence, so
    // callers do not need to check this.
    //
    // Non-const so an optional on-disk clip can be dropped in over a
    // synthesised one (see override_clip_from_wav). Do that BEFORE start(),
    // or after stop(): the audio thread holds bare pointers into these clips
    // while it is running.
    SfxBank& bank() { return bank_; }
    const SfxBank& bank() const { return bank_; }

    // Pimpl so the playback backend's header stays inside device.cpp. It is a
    // ~90k-line single-header library; letting it leak into anything that
    // merely wants to know what an AudioDevice is would be a compile-time tax
    // on the whole host target.
    //
    // Declared PUBLIC — the backend's callbacks are plain C function pointers,
    // so they are free functions with no access to a private nested type. The
    // alternative is a friend declaration for a callback whose signature is
    // owned by a third party, which ages worse.
    struct Impl;

private:
    // Total PCM in the bank, in seconds. One startup log line.
    float bank_total_seconds_() const;

    Impl* impl_ = nullptr;

    VoiceMixer mixer_;
    SfxBank bank_;
    uint32_t sample_rate_ = 0;
    bool running_ = false;
};

}  // namespace apricot
