#!/usr/bin/env python3
"""Bake the shared plate atlas and C++ catalog from the authored state designs.

No random raster content, network fonts, per-car textures, or runtime font work.
The 2048-square atlas contains eight 512x256 blanks and eight glyph strips.
"""
import argparse
import io
import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
GLYPHS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789- '
FONT = ROOT / 'assets/fonts/BebasNeue-Regular.ttf'
LABEL = ROOT / 'assets/fonts/Roboto-Variable.ttf'

def font(size, label=False):
    return ImageFont.truetype(str(LABEL if label else FONT), size)

def text(draw, xy, value, face, fill):
    draw.text(xy, value, font=face, fill=fill, anchor='mm')

def blank(spec):
    img = Image.new('RGB', (512, 256), spec['paper'])
    d = ImageDraw.Draw(img)
    d.rounded_rectangle((3, 3, 508, 252), radius=20, outline='#aaa99e', width=6)
    d.rounded_rectangle((12, 12, 499, 243), radius=15, outline=spec['ink'], width=2)
    d.rounded_rectangle((17, 17, 494, 73), radius=10, fill=spec['accent'])
    title = "O'HAVEN" if spec['state'] == 'OHaven' else 'FLORANGIA'
    text(d, (256, 44), title, font(39), '#fff5db')
    # The serial field (y=84..180) stays solid for the opaque glyph quads.
    # Tiny state seal and a skyline/sun motif leave the main number uncluttered.
    if spec['state'] == 'OHaven':
        d.polygon([(42,65),(46,32),(53,32),(57,65)], fill='#fff5db')
        d.rectangle((44,28,55,35), fill='#fff5db')
        d.polygon([(42,28),(50,20),(58,28)], fill='#fff5db')
        d.line((33,62,64,62), fill='#fff5db', width=3)
        d.line((453,205,464,195,478,205,490,196), fill=spec['accent'], width=3)
    else:
        d.ellipse((33,28,62,57), fill='#fff5db')
        d.line((29,63,44,59,58,63,70,59), fill='#fff5db', width=3)
        d.arc((450,189,486,225),180,360,fill=spec['accent'],width=3)
        d.line((448,209,489,209),fill=spec['accent'],width=3)
    slogan = spec['slogan'].replace(' • ', ' / ')
    text(d, (256, 210), slogan, font(23), spec['ink'])
    for x in (88,424):
        for y in (23,232):
            d.ellipse((x-5,y-3,x+5,y+3),fill='#73766e')
            d.line((x-3,y,x+3,y), fill='#dcded4', width=1)
    return img

def sample_serial(spec):
    letters=iter('HKMV'); numbers=iter('48271')
    return ''.join(next(letters) if c=='@' else next(numbers) if c=='#' else c for c in spec['pattern'])

def build():
    specs=json.loads((ROOT/'assets/data/license_plates.json').read_text())
    expected=[(s,t) for s in ('OHaven','Florangia') for t in ('Standard','Heritage','Commercial','Government')]
    assert [(s['state'],s['series']) for s in specs]==expected
    atlas=Image.new('RGB',(2048,2048),'#222222')
    sheet=Image.new('RGB',(1184,1400),'#111c24'); sd=ImageDraw.Draw(sheet)
    text(sd,(592,58),'PROBABLE CAUSE / STATE PLATES',font(43),'#f2e9d6')
    lines=[]
    for i,s in enumerate(specs):
        assert len(s['pattern'])<=10
        base=blank(s); atlas.paste(base,((i%2)*512,(i//2)*256))
        for j,c in enumerate(GLYPHS):
            glyph=Image.new('RGB',(48,128),s['paper']); gd=ImageDraw.Draw(glyph)
            text(gd,(24,64),c,font(88),s['ink'])
            atlas.paste(glyph,(j*48,1024+i*128))
        example=base.copy(); ed=ImageDraw.Draw(example)
        serial=sample_serial(s); advance=432/len(serial)
        for j,c in enumerate(serial):
            tile=atlas.crop((GLYPHS.index(c)*48,1040+i*128,GLYPHS.index(c)*48+48,1136+i*128))
            tile=tile.resize((round(advance),96),Image.Resampling.LANCZOS)
            example.paste(tile,(round(40+j*advance),84))
        x=56+(i//4)*592; y=112+(i%4)*318
        sheet.paste(example,(x,y))
        text(sd,(x+256,y+280),s['name'].upper()+' / '+s['series'].upper(),font(23),'#b7c2c7')
        lines.append('    {city::StateId::%s, PlateSeries::%s, %s, %s, %s},' %
                     (s['state'],s['series'],json.dumps(s['name']),json.dumps(s['pattern']),json.dumps(s['slogan'],ensure_ascii=False)))
    outputs={ROOT/'src/game/license_plate_catalog.inc': ('// Generated by tools/make_license_plates.py; edit assets/data/license_plates.json.\n'+'\n'.join(lines)+'\n').encode()}
    for path,img in [(ROOT/'assets/textures/vehicles/common/license_plates.png',atlas),(ROOT/'build/license-plates/designs.png',sheet)]:
        data=io.BytesIO();img.save(data,format='PNG');outputs[path]=data.getvalue()
    return outputs

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for path,data in build().items():
        if args.check:
            if 'build' not in path.relative_to(ROOT).parts:
                assert path.exists() and path.read_bytes()==data, f'Stale generated plate asset: {path}'
        else:
            path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(data)
    print('License plate catalog and atlas verified.' if args.check else 'Baked eight state plate designs and serial glyphs.')
