#!/usr/bin/env python3
"""Bake Roboto Bold outlines for roadside signs (no runtime font dependency).

Run with Python + fonttools, skia-pathops, shapely, numpy and mapbox-earcut.
Verified with versions 4.60.2, 0.8.0.post2, 2.0.7, 2.0.2 and 2.1.0 respectively.
Source: https://github.com/google/fonts/tree/main/ofl/roboto
The original variable font and OFL license are kept in assets/fonts.
"""
from pathlib import Path

import mapbox_earcut
import numpy as np
from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont
from fontTools.ttLib.removeOverlaps import removeOverlaps
from fontTools.varLib.instancer import instantiateVariableFont
from shapely import make_valid
from shapely.affinity import translate
from shapely.geometry import Polygon
from shapely.ops import unary_union

ROOT = Path(__file__).resolve().parents[1]


class OutlinePen(BasePen):
    def __init__(self, glyphs):
        super().__init__(glyphs)
        self.rings = []

    def _moveTo(self, p):
        self.points = [p]

    def _lineTo(self, p):
        self.points.append(p)

    def _qCurveToOne(self, control, end):
        start = self._getCurrentPoint()
        # Eight samples per quadratic keep curves smooth at sign scale.
        for step in range(1, 9):
            t = step / 8
            self.points.append(tuple((1-t)**2 * start[i] +
                                     2*(1-t)*t * control[i] + t*t * end[i]
                                     for i in range(2)))

    def _closePath(self):
        self.rings.append(make_valid(Polygon(self.points)))


def outline(font, text):
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    shapes, cursor = [], 0
    for char in text:
        name = cmap[ord(char)]
        pen = OutlinePen(glyphs)
        glyphs[name].draw(pen)
        shape = Polygon()
        # XOR nested contours preserves the open counters in O, P, D and A.
        for ring in pen.rings:
            shape = shape.symmetric_difference(ring)
        shapes.append(translate(shape, xoff=cursor))
        cursor += glyphs[name].width
    return unary_union(shapes)


def main():
    font = instantiateVariableFont(TTFont(ROOT / "assets/fonts/Roboto-Variable.ttf"),
                                   {"wght": 700, "wdth": 100})
    removeOverlaps(font)
    lines = ["// Generated by tools/make_road_sign_font.py; do not edit.",
             "// Roboto Bold, Google Fonts. License: assets/fonts/Roboto-OFL.txt.",
             "#pragma once", "#include <array>", "#include <glm/vec2.hpp>",
             "namespace apricot::road_sign_detail {"]
    for name, text in [("Stop", "STOP"), ("Yield", "YIELD"), ("AllWay", "ALL WAY")]:
        shape = outline(font, text)
        x0, y0, x1, y1 = shape.bounds
        triangles = []
        for polygon in shape.geoms:
            rings = [list(r.coords)[:-1] for r in [polygon.exterior, *polygon.interiors]]
            points = np.array([p for ring in rings for p in ring], dtype=np.float64)
            ends = np.cumsum([len(r) for r in rings], dtype=np.uint32)
            indices = mapbox_earcut.triangulate_float64(points, ends)
            triangles.extend(Polygon(points[indices[i:i+3]])
                             for i in range(0, len(indices), 3))
        # Reject triangulation gaps or accidentally filled letter counters.
        assert abs(sum(t.area for t in triangles) - shape.area) < 1e-5
        lines.append(f"inline constexpr float k{name}Aspect = {(x1-x0)/(y1-y0):.8f}f;")
        lines.append(f"inline constexpr std::array<glm::vec2, {len(triangles)*3}> k{name}Letters{{{{")
        for triangle in triangles:
            points = list(triangle.exterior.coords)[:3]
            a, b, c = points
            if (b[0]-a[0])*(c[1]-a[1]) - (b[1]-a[1])*(c[0]-a[0]) < 0:
                points.reverse()
            lines.append("    " + ", ".join(
                f"{{{(x-(x0+x1)/2)/(y1-y0):.8f}f, {(y-(y0+y1)/2)/(y1-y0):.8f}f}}"
                for x, y in points) + ",")
        lines.append("}};")
    lines.append("} // namespace apricot::road_sign_detail\n")
    (ROOT / "src/app/road_sign_font.h").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
